### ISSUE TITLE
Make an executable for Windows Mac and Linux

### ISSUE THREAD

**Issue by dcritchlow** [BatDev0/Python-TerminalCommands#7]
Make an executable so that those who don’t have python installed on their system can still use the functionality. 

We may be able to use Pyinstaller https://www.pyinstaller.org/

Here is a list of other alternative programs
https://docs.python-guide.org/shipping/freezing/

**Comment by BatDev0** [comment]
I will test the pyinstaller.org out. Thanks

**Comment by BatDev0** [comment]
@dcritchlow, If I made an exe. Like I did run it. How would I do the commands? It would just close the terminal since there are no commands to do.
